### ISSUE TITLE
bug: in production - crashes if no recipes on redirect to dashboard

### ISSUE THREAD

**Issue by JoarHansson** [sirisayshello/recipe-declutter#251]
for example if you have one recipe left and delete it - you get redirected to dashboard and get this error displayed on the screen:

`Application error: a client-side exception has occurred (see the browser console for more information).`

This shows in the server console:
```
TypeError: Cannot read properties of undefined (reading 'title')
    at P (/app/.next/server/app/dashboard/page.js:1:18498)
    at nj (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
    at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
    at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560) {
  digest: '28258159'
}
```

**Comment by sirisayshello** [comment]
fixed in #270
